version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      - sudo yum -y install terraform

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Running Terraform Plan and Apply..."
      - terraform plan -out=tfplan
      # The -auto-approve flag is essential for non-interactive environments like CodeBuild
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - "**/*"