[project]
name = "ragaws"
version = "0.1.0"
description = "Project RAG on AWS"
authors = [
    {name = "Reasy94",email = "desalvialuca@yahoo.it"}
]
requires-python = "^3.12"
dependencies = [
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "onnxruntime (>=1.24.1,<2.0.0)",
    "tokenizers (>=0.22.2,<0.23.0)",
    "boto3 (>=1.42.52,<2.0.0)",
    "pdfplumber (>=0.11.9,<0.12.0)",
    "langchain (>=1.2.10,<2.0.0)",
    "langchain-text-splitters (>=1.1.1,<2.0.0)",
    "camelot-py[cv] (>=1.0.9,<2.0.0)",
    "tabula-py (>=2.10.0,<3.0.0)",
    "fitz (>=0.0.1.dev2,<0.0.2)",
    "pymupdf (>=1.27.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
